version: '3.8'

services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL: ${DATABASE_URL}
      - JWT_SECRET: ${JWT_SECRET}
      - NODE_ENV: development
    volumes:
      - .:/app
      - /app/node_modules
    command: yarn dev
  
#   postgres:
#     image: postgres:15
#     ports:
#       - "5432:5432"
#     environment:
#       - POSTGRES_DB: ${POSTGRES_DB}
#       - POSTGRES_USER: ${POSTGRES_USER}
#       - POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -U postgres"]
#       interval: 10s
#       timeout: 5s
#       retries: 5

# volumes:
#   postgres_data:
